### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by garethmcc** [rayperea/asusZenBookProDuoScreenBrightnessService#1]
Wasn't sure how else to get in touch but since I am looking to potentially get one of these machines I was wondering if you could provide any insight as to how good or not it is on Manjaro Gnome? There isn't a lot of reviews of this running under Linux

**Comment by rayperea** [comment]
You're right, there aren't a lot of people who use an Arch based distro on this machine. While I don't use Manjaro, I do use Arch Linux which is what Manjaro is based off of and It works great for me. I also use Gnome and it mostly works great. I have also installed Manjaro with Gnome on this computer in the past and it worked fine... pretty much the same as Arch. I do have to warn you of some of the things you'll face should you decide to purchase this machine.

1. The bottom screen can only have a resolution of 3840 x 1100. Anything different and the screen doesn't display correctly. You can use xrandr to scale the contents screen (which is what I do) but changing the resolution has never worked for me

2. The brightness controls won't work without this script.. At least I haven't gotten them to work without this script.

I know that I've had other minor issues... your mileage may vary. You should also check out this repo for additional information regarding this machine on any linux distro: https://github.com/s-light/ASUS-ZenBook-Pro-Duo-UX581GV
